"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { AlertCircle, Loader2 } from "lucide-react";
import { ResourceConfig } from "@/lib/cms/types";
import { FieldInput } from "./FieldInput";
import { createClient } from "@/lib/supabase/client";
import { GradientButton } from "@/components/ui/GradientButton";
import { slugify } from "@/lib/utils";
import { getPublicPaths, RevalidateTarget } from "@/lib/cms/revalidate-paths";

async function revalidatePublicPaths(targets: RevalidateTarget[]) {
  try {
    await fetch("/api/revalidate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ targets }) });
  } catch {
    // Best-effort — the live site will still catch up on its own within
    // the page's normal cache window even if this call fails.
  }
}

interface ResourceFormProps {
  resource: ResourceConfig;
  initialValues?: Record<string, unknown>;
  isNew: boolean;
  /** Called instead of navigating back to the list — used for a singleton
   * resource, which has no list to return to. */
  onSaved?: () => void;
}

export function ResourceForm({ resource, initialValues, isNew, onSaved }: ResourceFormProps) {
  const router = useRouter();
  const [values, setValues] = useState<Record<string, unknown>>(() => ({ ...(resource.defaultValues ?? {}), ...(initialValues ?? {}) }));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [slugTouched, setSlugTouched] = useState(!isNew);

  function setField(key: string, value: unknown) {
    setValues((prev) => {
      const next = { ...prev, [key]: value };
      // Auto-fill the slug from the title field until the user edits the
      // slug themselves — after that, their edits always win.
      if (resource.slugField && key === resource.titleField && !slugTouched) {
        next[resource.slugField] = slugify(String(value ?? ""));
      }
      if (resource.slugField && key === resource.slugField) {
        setSlugTouched(true);
      }
      return next;
    });
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSaving(true);
    setError(null);
    setSaved(false);

    try {
      const supabase = createClient();
      const payload = { ...values };

      if (resource.singleton) {
        // Always exactly one row — upsert it rather than deciding between
        // insert/update, since it may or may not exist yet.
        payload[resource.primaryKey] = resource.singletonId;
        const { error } = await supabase.from(resource.table).upsert(payload, { onConflict: resource.primaryKey });
        if (error) throw new Error(error.message);

        await revalidatePublicPaths(getPublicPaths(resource.key, payload));

        setSaving(false);
        setSaved(true);
        if (onSaved) onSaved();
        router.refresh();
        return;
      }

      // id is generated by the database for uuid primary keys; only send it
      // when this resource uses a human-chosen text id (faqs, appointment_types).
      if (isNew && resource.primaryKey === "id" && !resource.fields.some((f) => f.key === "id")) {
        delete payload.id;
      }

      const query = isNew ? supabase.from(resource.table).insert(payload) : supabase.from(resource.table).update(payload).eq(resource.primaryKey, initialValues?.[resource.primaryKey]);

      const { error } = await query;
      if (error) throw new Error(error.message);

      await revalidatePublicPaths(getPublicPaths(resource.key, payload));

      router.push(`/admin/content/${resource.key}`);
      router.refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong saving this.");
      setSaving(false);
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {resource.fields.map((field) => (
        <div key={field.key}>
          <label className="mb-1.5 block text-sm font-semibold text-navy-800">
            {field.label}
            {field.required && <span className="ml-1 text-red-500">*</span>}
          </label>
          {field.helpText && field.type !== "image" && field.type !== "video" && <p className="mb-1.5 text-xs text-navy-400">{field.helpText}</p>}
          <FieldInput field={field} value={values[field.key]} onChange={(v) => setField(field.key, v)} />
        </div>
      ))}

      {error && (
        <div className="flex items-start gap-2 rounded-xl bg-red-50 px-3 py-2.5 text-sm text-red-700">
          <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      <div className="flex items-center gap-3 border-t border-navy-100 pt-6">
        <GradientButton type="submit" icon={false} disabled={saving}>
          {saving ? (
            <span className="flex items-center gap-2">
              <Loader2 className="h-4 w-4 animate-spin" /> Saving…
            </span>
          ) : isNew ? (
            `Create ${resource.singularLabel}`
          ) : (
            "Save changes"
          )}
        </GradientButton>
        {resource.singleton ? (
          saved && <span className="text-sm font-medium text-green-600">Saved — live on the site now.</span>
        ) : (
          <button type="button" onClick={() => router.push(`/admin/content/${resource.key}`)} className="rounded-full px-6 py-3 text-sm font-semibold text-navy-500 hover:bg-navy-50">
            Cancel
          </button>
        )}
      </div>
    </form>
  );
}
