import { ResourceConfig } from "./types";
import { SITE_SETTINGS_DEFAULTS } from "./site-settings";

const CONTENT_CATEGORIES = [
  "immigration",
  "tax",
  "benefits",
  "employment",
  "family",
  "business",
  "housing",
  "citizenship",
  "legal-rights",
  "money",
  "life-in-the-uk",
].map((v) => ({ value: v, label: v.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()) }));

const SERVICE_CATEGORIES = ["immigration", "tax", "benefits", "general"].map((v) => ({
  value: v,
  label: v[0].toUpperCase() + v.slice(1),
}));

export const resources: ResourceConfig[] = [
  {
    key: "services",
    table: "services",
    label: "Services",
    singularLabel: "Service",
    description: "The service pages under Immigration, Tax and Benefits — what you offer, who it's for, and how the process works.",
    primaryKey: "id",
    slugField: "slug",
    titleField: "title",
    subtitleField: "category",
    orderBy: { column: "sort_order", ascending: true },
    defaultValues: { category: "immigration", who_its_for: [], what_we_help_with: [], process: [], documents_needed: [], typical_questions: [], sort_order: 0 },
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "slug", label: "URL slug", type: "text", required: true, helpText: "Used in the page address, e.g. /services/immigration/spouse-partner-visa" },
      { key: "category", label: "Category", type: "select", required: true, options: SERVICE_CATEGORIES },
      { key: "short_description", label: "Short description", type: "textarea", required: true, helpText: "Shown on service cards and previews." },
      { key: "problem_statement", label: "Problem statement", type: "textarea", required: true, helpText: "The 'why this matters' framing at the top of the page." },
      { key: "who_its_for", label: "Who it's for", type: "string-array", itemLabel: "point" },
      { key: "what_we_help_with", label: "What we help with", type: "string-array", itemLabel: "point" },
      {
        key: "process",
        label: "Process steps",
        type: "object-array",
        itemLabel: "step",
        subFields: [
          { key: "step", label: "Step name", type: "text" },
          { key: "description", label: "Description", type: "textarea" },
        ],
      },
      { key: "documents_needed", label: "Documents needed", type: "string-array", itemLabel: "document" },
      {
        key: "typical_questions",
        label: "Typical questions",
        type: "object-array",
        itemLabel: "question",
        subFields: [
          { key: "question", label: "Question", type: "text" },
          { key: "answer", label: "Answer", type: "textarea" },
        ],
      },
      { key: "related_calculators", label: "Related calculator IDs", type: "string-array", itemLabel: "calculator id", helpText: "The id of a calculator (see /admin/content → Calculators), not its title." },
      { key: "related_guides", label: "Related guide slugs", type: "string-array", itemLabel: "guide slug" },
      { key: "sort_order", label: "Sort order", type: "number", helpText: "Lower numbers show first." },
    ],
  },
  {
    key: "guides",
    table: "guides",
    label: "Guides",
    singularLabel: "Guide",
    description: "The long-form guide articles under /guides — plain-English explainers with headings, lists and callouts.",
    primaryKey: "id",
    slugField: "slug",
    titleField: "title",
    subtitleField: "category",
    orderBy: { column: "title", ascending: true },
    defaultValues: { category: "tax", read_time_minutes: 5, needs_review: true, body: [], sources: [] },
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "slug", label: "URL slug", type: "text", required: true, helpText: "Used in the page address, e.g. /guides/tax/how-paye-tax-works" },
      { key: "category", label: "Category", type: "select", required: true, options: CONTENT_CATEGORIES },
      { key: "summary", label: "Summary", type: "textarea", required: true, helpText: "Shown on guide cards and previews." },
      { key: "read_time_minutes", label: "Read time (minutes)", type: "number" },
      { key: "last_reviewed", label: "Last reviewed", type: "date" },
      { key: "reviewer", label: "Reviewer name", type: "text" },
      { key: "needs_review", label: "Flag as needing legal review", type: "boolean", helpText: "Shows a 'needs review' badge in the admin — doesn't affect the public page." },
      { key: "body", label: "Guide content", type: "guide-body", required: true },
      { key: "related_calculators", label: "Related calculator IDs", type: "string-array", itemLabel: "calculator id" },
      { key: "related_services", label: "Related service slugs", type: "string-array", itemLabel: "service slug" },
      { key: "related_guides", label: "Related guide slugs", type: "string-array", itemLabel: "guide slug" },
      {
        key: "sources",
        label: "Sources",
        type: "object-array",
        itemLabel: "source",
        subFields: [
          { key: "label", label: "Label", type: "text" },
          { key: "url", label: "URL", type: "text" },
          { key: "publisher", label: "Publisher", type: "text" },
        ],
      },
      { key: "seo_description", label: "SEO description", type: "textarea", required: true },
    ],
  },
  {
    key: "faqs",
    table: "faqs",
    label: "FAQs",
    singularLabel: "FAQ",
    description: "Frequently asked questions shown across the site.",
    primaryKey: "id",
    titleField: "question",
    subtitleField: "category",
    orderBy: { column: "sort_order", ascending: true },
    defaultValues: { category: "general", sort_order: 0 },
    fields: [
      { key: "id", label: "ID", type: "text", required: true, helpText: "A short unique id, e.g. faq-12. Can't be changed once other content links to it." },
      { key: "category", label: "Category", type: "select", required: true, options: [{ value: "general", label: "General" }, ...CONTENT_CATEGORIES] },
      { key: "question", label: "Question", type: "text", required: true },
      { key: "answer", label: "Answer", type: "textarea", required: true },
      { key: "related_calculator", label: "Related calculator ID", type: "text" },
      { key: "related_guide", label: "Related guide slug", type: "text" },
      { key: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "testimonials",
    table: "testimonials",
    label: "Testimonials",
    singularLabel: "Testimonial",
    description: "The written client quotes shown on the homepage.",
    primaryKey: "id",
    titleField: "name",
    subtitleField: "service",
    orderBy: { column: "sort_order", ascending: true },
    defaultValues: { rating: 5, sort_order: 0 },
    fields: [
      { key: "name", label: "Client name", type: "text", required: true },
      { key: "service", label: "Service", type: "text", required: true, helpText: "e.g. Spouse Visa, Self-Assessment Tax" },
      { key: "quote", label: "Quote", type: "textarea", required: true },
      { key: "rating", label: "Rating (1-5)", type: "number" },
      { key: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "video_testimonials",
    table: "video_testimonials",
    label: "Video Testimonials",
    singularLabel: "Video Testimonial",
    description: "The 'Hear it from others' video cards on the homepage.",
    primaryKey: "id",
    titleField: "name",
    subtitleField: "service",
    orderBy: { column: "sort_order", ascending: true },
    defaultValues: { sort_order: 0 },
    fields: [
      { key: "name", label: "Client name", type: "text", required: true },
      { key: "service", label: "Service", type: "text", required: true },
      { key: "quote", label: "Quote", type: "textarea", required: true },
      { key: "poster_url", label: "Poster image", type: "image", required: true, helpText: "The still frame shown before the video plays. 9:16 portrait works best." },
      { key: "video_url", label: "Video", type: "video", required: true, helpText: "9:16 portrait video, a few seconds to a minute." },
      { key: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "updates",
    table: "updates",
    label: "Blog / Updates",
    singularLabel: "Update",
    description: "The 'See what's new' posts shown on the homepage and the Blog page.",
    primaryKey: "id",
    slugField: "slug",
    titleField: "title",
    subtitleField: "category",
    orderBy: { column: "published", ascending: false },
    defaultValues: { category: "immigration", is_published: true },
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "slug", label: "URL slug", type: "text", required: true },
      { key: "category", label: "Category", type: "select", required: true, options: CONTENT_CATEGORIES },
      { key: "summary", label: "Summary", type: "textarea", required: true, helpText: "Shown in the list/preview cards." },
      { key: "body", label: "Full post", type: "textarea", required: true },
      { key: "image_url", label: "Image", type: "image", helpText: "Optional — if left blank, a default image is used." },
      { key: "published", label: "Published date", type: "date", required: true },
      { key: "last_reviewed", label: "Last reviewed date", type: "date" },
      { key: "applies_from", label: "Applies from date", type: "date" },
      { key: "is_published", label: "Published (visible on the site)", type: "boolean", helpText: "Turn off to save a draft without showing it publicly." },
    ],
  },
  {
    key: "hero_slides",
    table: "hero_slides",
    label: "Hero Slides",
    singularLabel: "Hero Slide",
    description: "The rotating banner at the top of the homepage.",
    primaryKey: "id",
    titleField: "title",
    subtitleField: "subtitle",
    orderBy: { column: "sort_order", ascending: true },
    defaultValues: { cta_label: "Book a Call", cta_href: "/appointment", sort_order: 0 },
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "subtitle", label: "Subtitle", type: "textarea", required: true },
      { key: "cta_label", label: "Button label", type: "text", required: true },
      { key: "cta_href", label: "Button link", type: "text", required: true, helpText: "e.g. /appointment" },
      {
        key: "image_url",
        label: "Right banner media",
        type: "media",
        required: true,
        helpText: "Accepts a photo (jpg/png), a GIF, or a video (mp4/webm) — it displays correctly either way.",
      },
      {
        key: "card_media_url",
        label: "Left card background media (optional)",
        type: "media",
        helpText:
          "Shows faintly behind the navy card on the left — the navy tone stays dominant, this just adds subtle texture. Accepts a photo, GIF, or video. Leave blank to use the default photo.",
      },
      { key: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "appointment_types",
    table: "appointment_types",
    label: "Appointment Types",
    singularLabel: "Appointment Type",
    description: "The consultation types clients choose from when booking.",
    primaryKey: "id",
    titleField: "label",
    subtitleField: "duration_minutes",
    orderBy: { column: "sort_order", ascending: true },
    defaultValues: { duration_minutes: 30, sort_order: 0 },
    fields: [
      { key: "id", label: "ID", type: "text", required: true, helpText: "A short unique id, e.g. 30-min. Can't be changed once bookings reference it." },
      { key: "label", label: "Label", type: "text", required: true },
      { key: "duration_minutes", label: "Duration (minutes)", type: "number", required: true },
      { key: "description", label: "Description", type: "textarea", required: true },
      { key: "price_label", label: "Price label", type: "text", required: true, helpText: "e.g. £75 or Free" },
      { key: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "site_settings",
    table: "site_settings",
    label: "Site Settings",
    singularLabel: "Site Settings",
    description: "Business contact details, social links, the main navigation, the footer, and other text used on every page — changes here apply site-wide.",
    primaryKey: "id",
    titleField: "business_name",
    orderBy: { column: "id", ascending: true },
    singleton: true,
    singletonId: "default",
    defaultValues: {
      id: "default",
      business_name: SITE_SETTINGS_DEFAULTS.businessName,
      tagline: SITE_SETTINGS_DEFAULTS.tagline,
      description: SITE_SETTINGS_DEFAULTS.description,
      phone: SITE_SETTINGS_DEFAULTS.phone,
      email: SITE_SETTINGS_DEFAULTS.email,
      address: SITE_SETTINGS_DEFAULTS.address,
      hours: SITE_SETTINGS_DEFAULTS.hours,
      regulatory: SITE_SETTINGS_DEFAULTS.regulatory,
      search_placeholder: SITE_SETTINGS_DEFAULTS.searchPlaceholder,
      nav_cta_label: SITE_SETTINGS_DEFAULTS.navCtaLabel,
      nav_cta_href: SITE_SETTINGS_DEFAULTS.navCtaHref,
      footer_cta_eyebrow: SITE_SETTINGS_DEFAULTS.footerCtaEyebrow,
      footer_cta_heading: SITE_SETTINGS_DEFAULTS.footerCtaHeading,
      footer_cta_button_label: SITE_SETTINGS_DEFAULTS.footerCtaButtonLabel,
      copyright_text: SITE_SETTINGS_DEFAULTS.copyrightText,
      social_links: SITE_SETTINGS_DEFAULTS.socialLinks,
      main_nav: SITE_SETTINGS_DEFAULTS.mainNav,
      footer_links: SITE_SETTINGS_DEFAULTS.footerLinks,
    },
    fields: [
      { key: "business_name", label: "Business name", type: "text", required: true },
      { key: "tagline", label: "Tagline", type: "text" },
      { key: "description", label: "Description", type: "textarea", helpText: "Shown in the footer, and used for SEO." },
      { key: "phone", label: "Phone number", type: "text" },
      { key: "email", label: "Email address", type: "text" },
      { key: "address", label: "Office address", type: "text" },
      { key: "hours", label: "Opening hours", type: "text" },
      { key: "regulatory", label: "Regulatory information", type: "text", helpText: "e.g. SRA number — shown in the footer." },
      { key: "search_placeholder", label: "Search box placeholder text", type: "text" },
      { key: "nav_cta_label", label: "Nav bar button — label", type: "text", helpText: "The button in the top navigation, e.g. “Talk to Us”." },
      { key: "nav_cta_href", label: "Nav bar button — link", type: "text" },
      { key: "footer_cta_eyebrow", label: "Footer banner — small label above the heading", type: "text" },
      { key: "footer_cta_heading", label: "Footer banner — heading", type: "text" },
      { key: "footer_cta_button_label", label: "Footer banner — button label", type: "text" },
      { key: "copyright_text", label: "Copyright line", type: "text", helpText: "The current year is added in front of this automatically." },
      {
        key: "social_links",
        label: "Social links",
        type: "object-array",
        itemLabel: "social link",
        subFields: [
          { key: "label", label: "Platform name", type: "text" },
          { key: "href", label: "Profile URL", type: "text" },
          { key: "icon", label: "Icon", type: "text" },
        ],
        helpText: "Icon must be one of: Facebook, Instagram, Linkedin, Twitter, Youtube, Tiktok.",
      },
      {
        key: "main_nav",
        label: "Main navigation links",
        type: "object-array",
        itemLabel: "nav link",
        subFields: [
          { key: "label", label: "Label", type: "text" },
          { key: "href", label: "Link", type: "text" },
        ],
        helpText: "Shown left-to-right in the top navigation, in this order.",
      },
      {
        key: "footer_links",
        label: "Footer links",
        type: "object-array",
        itemLabel: "footer link",
        subFields: [
          { key: "group", label: "Column heading (e.g. Explore, Company, Legal)", type: "text" },
          { key: "label", label: "Label", type: "text" },
          { key: "href", label: "Link", type: "text" },
        ],
        helpText: "Links with the same column heading are grouped together in the footer, in the order you add them.",
      },
    ],
  },
];

export function getResource(key: string): ResourceConfig | undefined {
  return resources.find((r) => r.key === key);
}
